### ISSUE TITLE
Cookie example given in the docs not working

### ISSUE THREAD

**Issue by jibin2706** [Tarang11/fastify-csrf#9]
I tried using the same code from the docs but was getting this error
```json
{"statusCode":500,"error":"Internal Server Error","message":"invalid csrf token"}
```

Logs

```json
{"level":30,"time":1567671488738,"pid":15370,"hostname":"tss-H110M-H","msg":"Server listening at http://127.0.0.1:3000","v":1}
{"level":30,"time":1567671496941,"pid":15370,"hostname":"tss-H110M-H","reqId":1,"req":{"method":"GET","url":"/","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":45810},"msg":"incoming request","v":1}
{"level":30,"time":1567671496947,"pid":15370,"hostname":"tss-H110M-H","reqId":1,"res":{"statusCode":200},"responseTime":5.293844999745488,"msg":"request completed","v":1}
{"level":30,"time":1567671504128,"pid":15370,"hostname":"tss-H110M-H","reqId":2,"req":{"method":"POST","url":"/data","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":45868},"msg":"incoming request","v":1}
{"level":50,"time":1567671504132,"pid":15370,"hostname":"tss-H110M-H","reqId":2,"req":{"method":"POST","url":"/data","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":45868},"res":{"statusCode":500},"err":{"type":"Error","message":"invalid csrf token","stack":"Error: invalid csrf token\n    at Object.handleCsrf (/home/tss/csrf-test/node_modules/fastify-csrf/lib/fastifyCsrf.js:28:10)\n    at hookIterator (/home/tss/csrf-test/node_modules/fastify/lib/hooks.js:124:10)\n    at next (/home/tss/csrf-test/node_modules/fastify/lib/hooks.js:70:20)\n    at hookRunner (/home/tss/csrf-test/node_modules/fastify/lib/hooks.js:84:3)\n    at preValidationCallback (/home/tss/csrf-test/node_modules/fastify/lib/handleRequest.js:93:5)\n    at handler (/home/tss/csrf-test/node_modules/fastify/lib/handleRequest.js:70:5)\n    at done (/home/tss/csrf-test/node_modules/fastify/lib/contentTypeParser.js:115:7)\n    at Parser.contentParser [as fn] (/home/tss/csrf-test/node_modules/fastify-formbody/formbody.js:10:5)\n    at IncomingMessage.onEnd (/home/tss/csrf-test/node_modules/fastify/lib/contentTypeParser.js:185:25)\n    at IncomingMessage.emit (events.js:203:15)"},"msg":"invalid csrf token","v":1}
{"level":30,"time":1567671504133,"pid":15370,"hostname":"tss-H110M-H","reqId":2,"res":{"statusCode":500},"responseTime":4.723324000835419,"msg":"request completed","v":1}
```

Code
```js
const fastify = require("fastify")({ logger: true });
const fastifyCookie = require("fastify-cookie");
const fastifyFormBody = require("fastify-formbody");
const fastifyCSRF = require("fastify-csrf");

fastify.register(fastifyCookie);
fastify.register(fastifyFormBody);
fastify.register(fastifyCSRF, { cookie: true });

fastify.get("/", (request, reply) => {
  var form = `
      <form method = "post" action="/data">
         <input type="text" name"field_name"/>
         <input type="hidden" value="${request.csrfToken()}" 
     name="_csrf /* this token can be sent in request header as well */"/>
         <button type="submit">Submit</button>
      </form>
    `;
  reply.type("text/html").send(form);
});

fastify.post("/data", (request, reply) => {
  reply.send("Post successful");
});

fastify.listen(3000, err => {
  if (err) {
    process.exit(0);
  }
});
```

**Comment by Tarang11** [comment]
Please remove the comment /* this token can be sent in request header as well */ and make it name="_csrf" , this is used as documentation.

**Comment by jibin2706** [comment]
Does this package work with fastify-nextjs
